module.exports = {
  title: "Abi Studio",
  keywords: [
    "abi",
    "abistudio",
    "abiweddings",
    "abieskuvo",
    "eskuvo",
    "wedding",
    "svadba",
    "pusko mihaly",
    "pusko",
    "mikuku",
    "wedding video",
    "wedding cinematography",
    "wedding hungary",
    "eskuvoi video",
    "miskolc eskuvo",
    "esküvő",
    "esküvői videó",
    "miskolc esküvő",
    "magyar esküvő",
    "magyar eskuvo",
    "svadobne video",
    "eskuvo video",
    "esküvő video",
  ],
  description: "abi studio for weddings and music clips",
  author: "Yoghurt",
  trackingId: "TODO",//UA-119418003-5
  defaultLang: "hu",
  defaultPage: "Home",
  langTextMap: {
    //en: "English",
    hu: "Magyar",
    //sk: "Slovensky",
  },
};